### ISSUE TITLE
Relationships with empty arrays get removed

### ISSUE THREAD

**Issue by camilofsl** [weilandia/deserialize-json-api#20]
Hi,

When I deserialize an API response if one the relationship's value is empty that attribute is not inserted on the deserialized object.

Is there any way to fix this?

**Comment by hjJunior** [comment]
Facing same issue

**Comment by exSnake** [comment]
@weilandia Do you still maintain this repo?

**Comment by weilandia** [comment]
Sorry everyone! I had notifications muted on this repo for some reason.  @exSnake I don't actively work on this repo anymore but happy to fix this and/or add maintainers.

**Comment by weilandia** [comment]
@hjJunior or @camilofsl I know this is super old, but does https://github.com/weilandia/deserialize-json-api/pull/33 solve your issue?
