### ISSUE TITLE
Can we get a new NPM release?

### ISSUE THREAD

**Issue by haubey** [weilandia/deserialize-json-api#37]
Hi @weilandia, is it possible to get a new NPM version release for this project? Looks like the main branch here has some changes that better handle null resources, but the version published to NPM doesn't include these fixes. Thanks for your time!

**Comment by weilandia** [comment]
Done!  Do you use this lib in a production app? We don't use it anymore so lmk if you wan to be a maintainer.

**Comment by haubey** [comment]
@weilandia we do, and I think that's something I'd be open to!
