### ISSUE TITLE
Missing Relationship

### ISSUE THREAD

**Issue by exSnake** [weilandia/deserialize-json-api#41]
Straight to the point, I just cloned your repo and launched mapRelationships test with this data:

```js
const missingReference = {
  data: {
    type: "posts",
    id: "2291",
    attributes: {},
    relationships: {
      user: {
        data: {
          type: "users",
          id: "39",
        },
      },
      comments: {
        data: [
          {
            type: "comments",
            id: "7989",
          },
          {
            type: "comments",
            id: "7990",
          },
        ],
      },
    },
  },
  included: [
    {
      type: "users",
      id: "39",
      attributes: {},
      relationships: {},
    },
    {
      type: "users",
      id: "100",
      attributes: {},
      relationships: {},
    },
    {
      type: "comments",
      id: "7989",
      attributes: {},
      relationships: {
        user: {
          data: {
            type: "users",
            id: "39",
          },
        },
        pre: {
          data: {
            type: "comments",
            id: "7986",
          },
        },
      },
    },
    {
      type: "comments",
      id: "7986",
      attributes: {},
      relationships: {
        user: {
          data: {
            type: "users",
            id: "39",
          },
        },
      },
    },
    {
      type: "comments",
      id: "7990",
      attributes: {},
      relationships: {
        user: {
          data: {
            type: "users",
            id: "100",
          },
        },
        pre: {
          data: {
            type: "comments",
            id: "7989",
          },
        },
      },
    },
  ],
};

const missingReferenceExpectedResponse = {
  id: "2291",
  type: "posts",
  user: {
    type: "users",
    id: "39",
  },
  comments: [
    {
      type: "comments",
      id: "7989",
      user: {
        type: "users",
        id: "39",
      },
      pre: {
        type: "comments",
        id: "7986",
        user: {
          type: "users",
          id: "39",
        },
      },
    },
    {
      type: "comments",
      id: "7990",
      user: {
        type: "users",
        id: "100",
      },
      pre: {
        type: "comments",
        id: "7989",
        user: {
           type: "users",
           id: "39",
         },
      },
    },
  ],
};
```

But in the real result, the comment with id 7990, his pre relationship, has type and id but user relation is missing.

I was expecting the 7990->pre that is a child of the same type, to have a user associated, like the 7989->pre (7986) has, why is this happening? I think that it's related to the fact that the 7989 is already a relationship of posts so seem that his relationship get skipped, tried to figure out myself but can't debug it through the code

@weilandia can you help me understand the flow of your code, maybe If you run out of time I can try to fix it, I thought the problem could be in deserializeIncluded but can't find it.

**Comment by weilandia** [comment]
We haven't used this lib for 4 or 5 years now, but I can take a look and get back to you.

**Comment by exSnake** [comment]
> We haven't used this lib for 4 or 5 years now, but I can take a look and get back to you.

Yeah, i saw that on other issues, this is the only library I've found that allows you to do this and used in conjunction with laravel-jsonapi it becomes critical. As I told you I tried to do some debugging but I couldn't figure out where the problem is

**Comment by exSnake** [comment]
@weilandia did you had time to look at it?

**Comment by weilandia** [comment]
I just pushed a new version that adds this as a test case. The code was pretty old and bad in general, so I mostly rewrote it all and removed all the dependencies.

**Comment by exSnake** [comment]
> I just pushed a new version that adds this as a test case. The code was pretty old and bad in general, so I mostly rewrote it all and removed all the dependencies.

Thank you, nice thing you added comments, commit is very big didn't allow me to figure out where the problem was, anyway I'll do some testing, thank you very much
